### ISSUE TITLE
Incompatible with ModMenu (Ornithe b1.7.3)

### ISSUE THREAD

**Issue by kimoVoid** [tildejustin/optifabric#8]
Seems like this mod is not compatible with ModMenu on b1.7.3. The game launches without optifine (the mod itself works).

Tested with `beta_OptiFine_1.7.3_HD_G` and `beta_OptiFine_1.7.3_HD_S_G`. All latest versions.

```
java.lang.RuntimeException: Mixin transformation of net.minecraft.unmapped.C_3831727 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.client.Minecraft.m_6675021(Minecraft.java:311)
	at net.minecraft.client.Minecraft.run(Minecraft.java:716)
	at net.minecraft.client.MinecraftApplet.handler$zzc000$legacy-lwjgl3$onAppletInit(MinecraftApplet.java:1066)
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java)
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletLauncher.init(AppletLauncher.java:138)
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletFrame.launch(AppletFrame.java:125)
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletMain.run(AppletMain.java:44)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 25 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.modmenu.json:MixinTextRenderer from mod modmenu] from phase [DEFAULT] in config [mixins.modmenu.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 28 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field f_7122498 was not located in the target class net.minecraft.unmapped.C_3831727. Using refmap modmenu-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 28 more
```

**Comment by kimoVoid** [comment]
oops completely neglected the existence of [this](https://github.com/tildejustin/modmenu-ornithe)
closing this since it works with that ^^
